-- HAMA PRODUCTION-READY SUPABASE SCHEMA
-- Safe to re-run in Supabase SQL Editor.

create extension if not exists pgcrypto;
create extension if not exists citext;

-- =========================
-- ENUMS
-- =========================
do $$ begin
  create type public.property_status as enum ('draft','active','reserved','rented','suspended','expired');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.media_type as enum ('photo','video');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.room_type as enum ('sitting_room','bedroom','kitchen','washroom','exterior');
exception when duplicate_object then null; end $$;

-- =========================
-- PROFILES
-- =========================
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  avatar_path text,
  is_verified boolean not null default false,
  is_admin boolean not null default false,
  notice_confirmed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =========================
-- LOCATION REFERENCE DATA
-- =========================
create table if not exists public.locations (
  id bigint generated by default as identity primary key,
  hood text not null,
  area text not null,
  slug text generated always as (lower(regexp_replace(trim(hood || '-' || area), '[^a-zA-Z0-9]+', '-', 'g'))) stored,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (hood, area),
  unique (slug)
);

-- =========================
-- PROPERTIES / LISTINGS
-- =========================
create table if not exists public.properties (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete restrict,
  location_id bigint references public.locations(id) on delete restrict,
  hood text not null,
  area text not null,
  house_type text not null check (house_type in ('Bedsitter','1 Bedroom','2 Bedrooms','3 Bedrooms')),
  rent integer not null check (rent > 0 and rent <= 100000000),
  deposit integer check (deposit is null or deposit >= 0),
  vacancy_date date not null,
  water text,
  security text,
  road text,
  internet text,
  parking text,
  pets_allowed boolean,
  description text check (description is null or length(description) <= 3000),
  status public.property_status not null default 'draft',
  published_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint properties_area_consistency foreign key (location_id) references public.locations(id) on delete restrict
);

-- =========================
-- PROPERTY MEDIA
-- =========================
create table if not exists public.property_media (
  id uuid primary key default gen_random_uuid(),
  property_id uuid not null references public.properties(id) on delete cascade,
  room_type public.room_type,
  media_type public.media_type not null,
  storage_path text not null unique,
  captured_at timestamptz,
  latitude numeric(9,6),
  longitude numeric(9,6),
  ai_verified boolean not null default false,
  freshness_verified boolean not null default false,
  width integer,
  height integer,
  duration_seconds integer,
  file_size_bytes bigint,
  checksum text,
  created_at timestamptz not null default now(),
  constraint media_video_duration check (duration_seconds is null or (duration_seconds >= 1 and duration_seconds <= 30))
);

-- =========================
-- USER ACCESS / POST-TO-UNLOCK
-- =========================
create table if not exists public.hunting_access (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  unlocked_at timestamptz not null default now(),
  unlocked_by_property_id uuid references public.properties(id) on delete set null
);

-- =========================
-- FAVORITES
-- =========================
create table if not exists public.favorites (
  user_id uuid not null references public.profiles(id) on delete cascade,
  property_id uuid not null references public.properties(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(user_id, property_id)
);

-- =========================
-- CONVERSATIONS / MESSAGES
-- =========================
create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  property_id uuid references public.properties(id) on delete set null,
  created_by uuid not null references public.profiles(id) on delete restrict,
  other_user_id uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  unique(property_id, created_by, other_user_id),
  constraint conversation_different_users check (created_by <> other_user_id)
);

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete restrict,
  body text not null check (length(trim(body)) between 1 and 4000),
  created_at timestamptz not null default now(),
  read_at timestamptz
);

-- =========================
-- NOTIFICATIONS
-- =========================
create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  type text not null,
  title text not null,
  body text,
  payload jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

-- =========================
-- REPORTS / AUDIT
-- =========================
create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  property_id uuid not null references public.properties(id) on delete cascade,
  reporter_id uuid references public.profiles(id) on delete set null,
  reason text not null,
  details text,
  status text not null default 'open' check (status in ('open','reviewing','resolved','dismissed')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- =========================
-- INDEXES
-- =========================
create index if not exists idx_locations_hood_area on public.locations(hood, area);
create index if not exists idx_properties_active_search on public.properties(status, hood, area, house_type, rent, vacancy_date);
create index if not exists idx_properties_owner on public.properties(owner_id, created_at desc);
create index if not exists idx_properties_vacancy on public.properties(vacancy_date) where status = 'active';
create index if not exists idx_media_property on public.property_media(property_id, room_type, created_at);
create index if not exists idx_messages_conversation on public.messages(conversation_id, created_at);
create index if not exists idx_notifications_user on public.notifications(user_id, created_at desc);
create index if not exists idx_reports_status on public.reports(status, created_at desc);

-- =========================
-- COMMON FUNCTIONS
-- =========================
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists trg_properties_updated_at on public.properties;
create trigger trg_properties_updated_at before update on public.properties
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles(id, full_name, phone)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', ''), coalesce(new.phone, new.raw_user_meta_data->>'phone'))
  on conflict (id) do nothing;
  return new;
end $$;

drop trigger if exists trg_auth_user_profile on auth.users;
create trigger trg_auth_user_profile after insert on auth.users
for each row execute function public.handle_new_user();

-- Enforce that published listings have the required media and a valid vacancy date.
create or replace function public.validate_property_publish()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  media_count integer;
begin
  if new.status = 'active' then
    if new.published_at is null then new.published_at = now(); end if;
    if new.vacancy_date < current_date then
      raise exception 'Vacancy date cannot be in the past';
    end if;
    select count(*) into media_count
    from public.property_media
    where property_id = new.id and media_type = 'photo' and ai_verified = true and freshness_verified = true;
    if media_count < 4 then
      raise exception 'A listing needs 4 verified room photos before it can be published';
    end if;
  end if;
  return new;
end $$;

drop trigger if exists trg_validate_property_publish on public.properties;
create constraint trigger trg_validate_property_publish
after insert or update of status, vacancy_date on public.properties
initially deferred for each row execute function public.validate_property_publish();

-- Expire listings automatically when they are far past vacancy or explicitly expired.
create or replace function public.expire_old_listings()
returns void language plpgsql security definer set search_path = public as $$
begin
  update public.properties
  set status = 'expired', updated_at = now()
  where status = 'active' and vacancy_date < current_date - 30;
end $$;

-- Unlock browsing only after a user has a published property.
create or replace function public.unlock_hunting_access(p_property_id uuid)
returns public.hunting_access language plpgsql security definer set search_path = public as $$
declare
  p public.properties;
  result public.hunting_access;
begin
  select * into p from public.properties where id = p_property_id and owner_id = auth.uid() and status = 'active';
  if p.id is null then raise exception 'You can only unlock access with your own active listing'; end if;
  insert into public.hunting_access(user_id, unlocked_by_property_id)
  values(auth.uid(), p_property_id)
  on conflict (user_id) do update set unlocked_by_property_id = excluded.unlocked_by_property_id;
  select * into result from public.hunting_access where user_id = auth.uid();
  return result;
end $$;

-- =========================
-- ROW LEVEL SECURITY
-- =========================
alter table public.profiles enable row level security;
alter table public.locations enable row level security;
alter table public.properties enable row level security;
alter table public.property_media enable row level security;
alter table public.hunting_access enable row level security;
alter table public.favorites enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.notifications enable row level security;
alter table public.reports enable row level security;
alter table public.audit_log enable row level security;

-- Profiles are private; expose only a deliberately-safe public projection.
drop policy if exists profiles_public_read on public.profiles;
drop policy if exists profiles_self_read on public.profiles;
create policy profiles_self_read on public.profiles for select using (auth.uid() = id);
drop view if exists public.public_profiles;
create view public.public_profiles as
select id, full_name, avatar_path, is_verified, created_at
from public.profiles;

drop policy if exists profiles_self_update on public.profiles;
create policy profiles_self_update on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);
drop policy if exists profiles_self_insert on public.profiles;
create policy profiles_self_insert on public.profiles for insert with check (auth.uid() = id);

-- Locations are public reference data
 drop policy if exists locations_public_read on public.locations;
create policy locations_public_read on public.locations for select using (is_active = true);

-- Listings: everyone may read active listings, owners can manage own rows.
drop policy if exists properties_public_active_read on public.properties;
create policy properties_public_active_read on public.properties for select using (status = 'active' or owner_id = auth.uid());
drop policy if exists properties_owner_insert on public.properties;
create policy properties_owner_insert on public.properties for insert with check (auth.uid() = owner_id);
drop policy if exists properties_owner_update on public.properties;
create policy properties_owner_update on public.properties for update using (auth.uid() = owner_id) with check (auth.uid() = owner_id);
drop policy if exists properties_owner_delete on public.properties;
create policy properties_owner_delete on public.properties for delete using (auth.uid() = owner_id);

-- Media: public read for active listings, owner can manage media for own property.
drop policy if exists media_public_read on public.property_media;
create policy media_public_read on public.property_media for select using (
  exists (select 1 from public.properties p where p.id = property_id and (p.status = 'active' or p.owner_id = auth.uid()))
);
drop policy if exists media_owner_insert on public.property_media;
create policy media_owner_insert on public.property_media for insert with check (
  exists (select 1 from public.properties p where p.id = property_id and p.owner_id = auth.uid())
);
drop policy if exists media_owner_update on public.property_media;
create policy media_owner_update on public.property_media for update using (
  exists (select 1 from public.properties p where p.id = property_id and p.owner_id = auth.uid())
) with check (
  exists (select 1 from public.properties p where p.id = property_id and p.owner_id = auth.uid())
);
drop policy if exists media_owner_delete on public.property_media;
create policy media_owner_delete on public.property_media for delete using (
  exists (select 1 from public.properties p where p.id = property_id and p.owner_id = auth.uid())
);

-- Access record is private to the owner.
drop policy if exists hunting_self_read on public.hunting_access;
create policy hunting_self_read on public.hunting_access for select using (auth.uid() = user_id);

-- Favorites
 drop policy if exists favorites_self_read on public.favorites;
create policy favorites_self_read on public.favorites for select using (auth.uid() = user_id);
drop policy if exists favorites_self_insert on public.favorites;
create policy favorites_self_insert on public.favorites for insert with check (auth.uid() = user_id);
drop policy if exists favorites_self_delete on public.favorites;
create policy favorites_self_delete on public.favorites for delete using (auth.uid() = user_id);

-- Conversations: participants only.
drop policy if exists conversations_participant_read on public.conversations;
create policy conversations_participant_read on public.conversations for select using (auth.uid() = created_by or auth.uid() = other_user_id);
drop policy if exists conversations_participant_insert on public.conversations;
create policy conversations_participant_insert on public.conversations for insert with check (auth.uid() = created_by);

-- Messages: participants only and sender must equal logged-in user.
drop policy if exists messages_participant_read on public.messages;
create policy messages_participant_read on public.messages for select using (
  exists (select 1 from public.conversations c where c.id = conversation_id and (c.created_by = auth.uid() or c.other_user_id = auth.uid()))
);
drop policy if exists messages_participant_insert on public.messages;
create policy messages_participant_insert on public.messages for insert with check (
  auth.uid() = sender_id and exists (select 1 from public.conversations c where c.id = conversation_id and (c.created_by = auth.uid() or c.other_user_id = auth.uid()))
);
drop policy if exists messages_receiver_update on public.messages;
create policy messages_receiver_update on public.messages for update using (
  exists (select 1 from public.conversations c where c.id = conversation_id and (c.created_by = auth.uid() or c.other_user_id = auth.uid()))
) with check (
  exists (select 1 from public.conversations c where c.id = conversation_id and (c.created_by = auth.uid() or c.other_user_id = auth.uid()))
);

-- Notifications are private.
drop policy if exists notifications_self_read on public.notifications;
create policy notifications_self_read on public.notifications for select using (auth.uid() = user_id);
drop policy if exists notifications_self_update on public.notifications;
create policy notifications_self_update on public.notifications for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Reports may be created by signed-in users. Only admins can read/manage.
drop policy if exists reports_user_insert on public.reports;
create policy reports_user_insert on public.reports for insert with check (auth.uid() = reporter_id);
drop policy if exists reports_admin_all on public.reports;
create policy reports_admin_all on public.reports for all using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin = true)) with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin = true));

-- Audit log is server/admin only via service role; authenticated users cannot read.
drop policy if exists audit_admin_read on public.audit_log;
create policy audit_admin_read on public.audit_log for select using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin = true));

-- =========================
-- STORAGE
-- =========================
insert into storage.buckets (id, name, public) values ('property-media','property-media',false)
on conflict (id) do update set public = false;

-- Public read is intentionally disabled. Hama should generate signed URLs from the server.
drop policy if exists media_storage_read on storage.objects;
create policy media_storage_read on storage.objects for select using (
  bucket_id = 'property-media' and (
    auth.uid()::text = (storage.foldername(name))[1]
    or exists (
      select 1 from public.properties p
      where p.owner_id = auth.uid() and p.id::text = (storage.foldername(name))[2]
    )
  )
);

drop policy if exists media_storage_insert on storage.objects;
create policy media_storage_insert on storage.objects for insert with check (
  bucket_id = 'property-media' and auth.uid()::text = (storage.foldername(name))[1]
);
drop policy if exists media_storage_update on storage.objects;
create policy media_storage_update on storage.objects for update using (
  bucket_id = 'property-media' and auth.uid()::text = (storage.foldername(name))[1]
) with check (
  bucket_id = 'property-media' and auth.uid()::text = (storage.foldername(name))[1]
);
drop policy if exists media_storage_delete on storage.objects;
create policy media_storage_delete on storage.objects for delete using (
  bucket_id = 'property-media' and auth.uid()::text = (storage.foldername(name))[1]
);

-- =========================
-- REALTIME
-- =========================
alter table public.messages replica identity full;
alter table public.notifications replica identity full;

do $$ begin
  alter publication supabase_realtime add table public.messages;
exception when duplicate_object then null; end $$;

do $$ begin
  alter publication supabase_realtime add table public.notifications;
exception when duplicate_object then null; end $$;

-- Optional seed check: run manually after importing locations.
select 'Hama schema installed' as status;
