-- Generated from lib/locations.ts; editable Hama Nairobi directory.
insert into public.locations (hood, area) values
('Westlands','Sarit Centre Area'),
('Westlands','Rhapta Road'),
('Westlands','Brookside'),
('Westlands','School Lane'),
('Westlands','Waiyaki Way'),
('Westlands','Westlands Road'),
('Westlands','General Mathenge'),
('Westlands','Muthangari'),
('Westlands','Kibagare'),
('Westlands','Deep Sea'),
('Parklands','1st Parklands Avenue'),
('Parklands','2nd Parklands Avenue'),
('Parklands','3rd Parklands Avenue'),
('Parklands','4th Parklands Avenue'),
('Parklands','5th Parklands Avenue'),
('Parklands','6th Parklands Avenue'),
('Parklands','Mpaka Road'),
('Parklands','Avenue Hospital Area'),
('Parklands','Highridge'),
('Highridge','Masari Road'),
('Highridge','Diamond Plaza Area'),
('Highridge','Limuru Road'),
('Highridge','Highridge Shopping Centre'),
('Highridge','Parklands Border'),
('Kangemi','Kangemi Market'),
('Kangemi','Sodom'),
('Kangemi','Mvuli Road'),
('Kangemi','Mountain View Border'),
('Kangemi','Waiyaki Way'),
('Mountain View','Mountain View Estate'),
('Mountain View','Lower Kabete Road'),
('Mountain View','Muthangari Border'),
('Mountain View','Kangemi Border'),
('Kitisuru','New Kitisuru'),
('Kitisuru','Old Kitisuru'),
('Kitisuru','Mwimuto'),
('Kitisuru','Tate Close'),
('Kitisuru','Kitisuru Road'),
('Loresho','Loresho Ridge'),
('Loresho','Loresho Estate'),
('Loresho','Kyuna'),
('Loresho','Kaptagat Road'),
('Loresho','Lower Kabete Border'),
('Spring Valley','Spring Valley Crescent'),
('Spring Valley','Peponi Road'),
('Spring Valley','Spring Valley Extension'),
('Spring Valley','Muthangari Border'),
('Gigiri','UN Avenue'),
('Gigiri','Village Market Area'),
('Gigiri','Warwick Centre Area'),
('Gigiri','Rosslyn Border'),
('Gigiri','Gigiri Drive'),
('Karura','Karura Forest Area'),
('Karura','Muthaiga North Border'),
('Karura','Ridgeways Border'),
('Runda','Old Runda'),
('Runda','Runda Mimosa'),
('Runda','Runda Meadows'),
('Runda','Runda Evergreen'),
('Runda','Runda Paradise'),
('Runda','Runda Gate'),
('Nyari','Nyari Estate'),
('Nyari','Nyari West'),
('Nyari','Rosslyn Border'),
('Nyari','Runda Border'),
('Muthaiga','Muthaiga Road'),
('Muthaiga','Old Muthaiga'),
('Muthaiga','New Muthaiga'),
('Muthaiga','Muthaiga North'),
('Muthaiga','Muthaiga Square'),
('Muthaiga North','Muthaiga North'),
('Muthaiga North','Marurui Border'),
('Muthaiga North','Garden Estate Border'),
('Githogoro','Githogoro Village'),
('Githogoro','Roysambu Border'),
('Githogoro','Runda Border'),
('Garden Estate','Garden Estate Road'),
('Garden Estate','Ridgeways'),
('Garden Estate','Marurui'),
('Garden Estate','Thome Border'),
('Marurui','Marurui Road'),
('Marurui','Garden Estate Border'),
('Marurui','Thome Border'),
('Marurui','Kilimani'),
('Marurui','Yaya Centre Area'),
('Marurui','Dennis Pritt'),
('Marurui','Lenana Road'),
('Marurui','Chania Avenue'),
('Marurui','Wood Avenue'),
('Marurui','Argwings Kodhek'),
('Marurui','Hurlingham Border'),
('Kileleshwa','Oloitoktok Road'),
('Kileleshwa','Mandera Road'),
('Kileleshwa','Gichugu Road'),
('Kileleshwa','Tabere Crescent'),
('Kileleshwa','Kileleshwa Crescent'),
('Kileleshwa','Kasuku Centre'),
('Hurlingham','Argwings Kodhek Road'),
('Hurlingham','Rose Avenue'),
('Hurlingham','Jabavu Road'),
('Hurlingham','Hurlingham Shopping Centre'),
('Hurlingham','Ring Road Kilimani'),
('Lavington','Lavington Green'),
('Lavington','James Gichuru'),
('Lavington','Chalbi Drive'),
('Lavington','Olenguruone Avenue'),
('Lavington','Valley Arcade'),
('Lavington','Gitanga Road'),
('Gatina','Gatina Market'),
('Gatina','Muthangari Drive'),
('Gatina','Riruta Border'),
('Gatina','Kawangware Border'),
('Kawangware','Stage 56'),
('Kawangware','Congo'),
('Kawangware','Coast'),
('Kawangware','Gatina'),
('Kawangware','Kawangware 46'),
('Kawangware','Kawangware Market'),
('Kawangware','Kabiro Border'),
('Kabiro','Kabiro'),
('Kabiro','Riruta Border'),
('Kabiro','Kawangware Border'),
('Kabiro','Wanyee Road'),
('Kabiro','Dagoretti'),
('Kabiro','Dagoretti Corner'),
('Kabiro','Satellite'),
('Kabiro','Kabiria'),
('Kabiro','Wanyee'),
('Kabiro','Mutuini Border'),
('Mutuini','Mutuini'),
('Mutuini','Dagoretti Corner Border'),
('Mutuini','Waithaka Border'),
('Ngando','Ngando Market'),
('Ngando','Ngando Road'),
('Ngando','Riruta Border'),
('Ngando','Mutuini Border'),
('Riruta','Riruta Satellite'),
('Riruta','Kabiria Road'),
('Riruta','PCEA Area'),
('Riruta','Riruta Centre'),
('Riruta','Kikuyu Road Border'),
('Uthiru','Uthiru Junction'),
('Uthiru','Cooperation'),
('Uthiru','Gichagi'),
('Uthiru','Uthiru Market'),
('Uthiru','Ruthimitu Border'),
('Ruthimitu','Ruthimitu'),
('Ruthimitu','Uthiru Border'),
('Ruthimitu','Dagoretti South Border'),
('Waithaka','Kwa Miti'),
('Waithaka','Central Waithaka'),
('Waithaka','Ndwaru Road'),
('Waithaka','Waithaka Shopping Centre'),
('Waithaka','Gitaru Border'),
('Kinoo','Stage 87'),
('Kinoo','Muthiga'),
('Kinoo','Regen'),
('Kinoo','Kinoo Market'),
('Kinoo','Gitaru Road'),
('Kinoo','Karen'),
('Kinoo','Hardy'),
('Kinoo','Miotoni'),
('Kinoo','Bogani'),
('Kinoo','Kerarapon'),
('Kinoo','Windy Ridge'),
('Kinoo','Karen Shopping Centre'),
('Kinoo','Langata Road'),
('Kinoo','Hardy Centre'),
('Langata','NHC Houses'),
('Langata','Phenom'),
('Langata','Southlands'),
('Langata','Onyonka'),
('Langata','Langata Shopping Centre'),
('Langata','Carnivore Area'),
('Langata','Wilson Airport Border'),
('Nairobi West','T-Mall Area'),
('Nairobi West','Gandhi Avenue'),
('Nairobi West','Kodi Road'),
('Nairobi West','Nairobi West Shopping Centre'),
('Mugumoini','Mugumoini'),
('Mugumoini','Carnivore Area'),
('Mugumoini','Langata Border'),
('South C','Bellevue'),
('South C','Five Star'),
('South C','Mugoya'),
('South C','Ole Sereni Area'),
('South C','South C Shopping Centre'),
('South C','Akila'),
('South C','Otiende Border'),
('Nyayo Highrise','Nyayo Highrise'),
('Nyayo Highrise','Otiende'),
('Nyayo Highrise','Mugoya'),
('Nyayo Highrise','South C Border'),
('Otiende','Otiende Estate'),
('Otiende','South C Border'),
('Otiende','Nyayo Highrise Border'),
('Otiende','Kibera'),
('Otiende','Laini Saba'),
('Otiende','Lindi'),
('Otiende','Makina'),
('Otiende','Gatwekera'),
('Otiende','Kianda'),
('Otiende','Kisumu Ndogo'),
('Otiende','Siranga'),
('Otiende','Mashimoni'),
('Otiende','Soweto East'),
('Otiende','Soweto West'),
('Laini Saba','Laini Saba'),
('Laini Saba','Railway'),
('Laini Saba','Kibera Drive'),
('Lindi','Lindi'),
('Lindi','Olympic Border'),
('Lindi','Kibera Drive'),
('Makina','Makina'),
('Makina','Ayany'),
('Makina','Woodley Border'),
('Woodley','Joseph Kang''ethe'),
('Woodley','Golf Course'),
('Woodley','Jamhuri Border'),
('Woodley','Kenyatta Golf Course'),
('Woodley','Woodley Estate'),
('Sarang''ombe','Sarang''ombe'),
('Sarang''ombe','Raila'),
('Sarang''ombe','Ayany'),
('Sarang''ombe','Kibera Drive'),
('Ayany','Ayany Estate'),
('Ayany','Makina'),
('Ayany','Sarang''ombe Border'),
('Ayany','Roysambu'),
('Ayany','TRM Area'),
('Ayany','Lumumba'),
('Ayany','Roysambu Gardens'),
('Ayany','Kamiti Road'),
('Ayany','Zimmerman Border'),
('Ayany','Githurai Border'),
('Githurai','Githurai 44'),
('Githurai','Githurai 45'),
('Githurai','Mwihoko Border'),
('Githurai','Githurai Market'),
('Githurai 44','Kwa Do'),
('Githurai 44','Climax'),
('Githurai 44','Sunrise'),
('Githurai 44','Jacaranda'),
('Githurai 44','Kiamumbi Border'),
('Githurai 44','Githurai 44 Market'),
('Githurai 45','Progressive'),
('Githurai 45','Kona'),
('Githurai 45','Mwihoko Border'),
('Githurai 45','Roundabout Area'),
('Githurai 45','Githurai 45 Market'),
('Kahawa','Kahawa Sukari'),
('Kahawa','Kahawa Wendani'),
('Kahawa','Kahawa West'),
('Kahawa','Kahawa Station'),
('Kahawa West','Railway'),
('Kahawa West','Kwa Ingo'),
('Kahawa West','Kamiti Corner'),
('Kahawa West','Congoni'),
('Kahawa West','Kahawa West Market'),
('Kahawa Sukari','Avenue First to Seventh'),
('Kahawa Sukari','Quickmart Area'),
('Kahawa Sukari','Sukari Presbyterian'),
('Kahawa Sukari','Kahawa Sukari Market'),
('Kahawa Wendani','Maguna''s Area'),
('Kahawa Wendani','Matopeni'),
('Kahawa Wendani','Clean Shelf Area'),
('Kahawa Wendani','Kahawa Wendani Market'),
('Zimmerman','Zimmerman Centre'),
('Zimmerman','Kasarani Border'),
('Zimmerman','TRM Border'),
('Zimmerman','Kiamumbi Road'),
('Zimmerman','Kasarani'),
('Zimmerman','Seasons'),
('Zimmerman','Car Wash'),
('Zimmerman','Clay City'),
('Zimmerman','Clayworks'),
('Zimmerman','TRM Drive'),
('Zimmerman','Hunters'),
('Zimmerman','Sunton'),
('Zimmerman','Sportsview'),
('Zimmerman','Maternity'),
('Zimmerman','Stima'),
('Zimmerman','Mwiki'),
('Zimmerman','Mwiki Terminus'),
('Zimmerman','Maji Mazuri'),
('Zimmerman','Gitari Marigo'),
('Zimmerman','Kwa DC'),
('Zimmerman','Tumaini'),
('Zimmerman','Warren'),
('Zimmerman','Kasarani-Mwiki Road'),
('Zimmerman','Clay City Centre'),
('Mwiki','Mwiki Town'),
('Mwiki','Mwiki Terminus'),
('Mwiki','Mwiki Stage'),
('Mwiki','Mwiki Road'),
('Mwiki','Mwiki Estate'),
('Mwiki','Maji Mazuri'),
('Clay City','Clay City Centre'),
('Clay City','Clay City Estate'),
('Clay City','Seasons Border'),
('Clay City','Mwiki Border'),
('Njiru','Chokaa Border'),
('Njiru','St. Monica'),
('Njiru','Njiru Centre'),
('Njiru','Kwa Chief'),
('Njiru','Ruai Road'),
('Ruai','Ruai Town'),
('Ruai','Shopping Centre'),
('Ruai','Sewage Area'),
('Ruai','Quickmart Area'),
('Ruai','Kamulu Road'),
('Ruai','Ruai Stage'),
('Chokaa','Stage 1'),
('Chokaa','Stage 2'),
('Chokaa','Stage 3'),
('Chokaa','Mwiki Road Link'),
('Chokaa','Njiru Border'),
('Kamulu','Kingoris'),
('Kamulu','Stage 26'),
('Kamulu','Kamulu Centre'),
('Kamulu','Joska Road'),
('Joska','Kantafu Border'),
('Joska','Market Area'),
('Joska','Joska Centre'),
('Malaa','KBC Area'),
('Malaa','Gated Courts'),
('Malaa','Malaa Centre'),
('Saika','Stage 29'),
('Saika','Mwengenye'),
('Saika','Saika Centre'),
('Saika','Ruaraka'),
('Saika','Baba Dogo'),
('Saika','Utalii'),
('Saika','Mathare North'),
('Saika','Lucky Summer'),
('Saika','Garden City Area'),
('Saika','Ruaraka Trading Centre'),
('Baba Dogo','Baba Dogo Centre'),
('Baba Dogo','Ruaraka Border'),
('Baba Dogo','Lucky Summer Border'),
('Utalii','Utalii College Area'),
('Utalii','Ruaraka Border'),
('Utalii','Thika Road'),
('Mathare North','Mathare North'),
('Mathare North','Baba Dogo Border'),
('Mathare North','Lucky Summer Border'),
('Lucky Summer','Lucky Summer Estate'),
('Lucky Summer','Baba Dogo Border'),
('Lucky Summer','Roysambu Border'),
('Korogocho','Korogocho A'),
('Korogocho','Korogocho B'),
('Korogocho','Korogocho Central'),
('Korogocho','Nyayo Village'),
('Korogocho','Imara Daima'),
('Korogocho','Villa Franca'),
('Korogocho','Sunrise Estate'),
('Korogocho','AA Area'),
('Korogocho','Imara Daima Shopping Centre'),
('Korogocho','Mombasa Road Border'),
('Kwa Njenga','Kwa Njenga'),
('Kwa Njenga','Mukuru Kwa Njenga'),
('Kwa Njenga','Jairos'),
('Kwa Njenga','Kwa Reuben Border'),
('Kwa Reuben','Kwa Reuben'),
('Kwa Reuben','Mukuru'),
('Kwa Reuben','Pipeline Border'),
('Pipeline','Plot 10'),
('Pipeline','Stage MP'),
('Pipeline','Avenue Area'),
('Pipeline','Pipeline Road'),
('Pipeline','Outering Road'),
('Kware','Kware'),
('Kware','Kwa Reuben Border'),
('Kware','Embakasi South Border'),
('Kware','Kariobangi North'),
('Kware','Kariobangi North'),
('Kware','Light Industries'),
('Kware','Dandora Border'),
('Kware','Outer Ring Road'),
('Dandora','Dandora Phase I'),
('Dandora','Dandora Phase II'),
('Dandora','Dandora Phase III'),
('Dandora','Dandora Phase IV'),
('Dandora','Dandora Phase V'),
('Dandora','Dump Site Area'),
('Kariobangi','Kariobangi North'),
('Kariobangi','Kariobangi South'),
('Kariobangi','Civil Servants'),
('Kariobangi','Light Industries'),
('Kariobangi','Kayole'),
('Kariobangi','Kayole North'),
('Kariobangi','Kayole Central'),
('Kariobangi','Kayole South'),
('Kariobangi','Soweto'),
('Kariobangi','Jikaze'),
('Kariobangi','Masimba'),
('Kariobangi','Kayole Junction'),
('Komarock','Sector 1'),
('Komarock','Sector 2'),
('Komarock','Sector 3'),
('Komarock','Sector 4'),
('Komarock','Komarock Heights'),
('Komarock','Komarock Centre'),
('Matopeni','Matopeni Junction'),
('Matopeni','Matopeni Estate'),
('Matopeni','Kayole Border'),
('Matopeni','Soweto Kayole'),
('Saika Estate','Saika'),
('Saika Estate','Stage 29'),
('Saika Estate','Mwengenye'),
('Saika Estate','Kayole Border'),
('Saika Estate','Embakasi'),
('Saika Estate','Embakasi Village'),
('Saika Estate','Embakasi Town'),
('Saika Estate','Nyayo Estate Border'),
('Saika Estate','Airport North Road'),
('Utawala','GSU Stage'),
('Utawala','Benedicta'),
('Utawala','Shooters'),
('Utawala','Mihango'),
('Utawala','Utawala Centre'),
('Utawala','Embakasi East Border'),
('Mihango','Mihango Centre'),
('Mihango','Utawala Border'),
('Mihango','Chokaa Road'),
('Upper Savanna','Upper Savanna'),
('Upper Savanna','Tena Border'),
('Upper Savanna','Embakasi Border'),
('Lower Savanna','Lower Savanna'),
('Lower Savanna','Donholm Border'),
('Lower Savanna','Embakasi Border'),
('Donholm','Phase 1'),
('Donholm','Phase 2'),
('Donholm','Phase 3'),
('Donholm','Phase 4'),
('Donholm','Phase 5'),
('Donholm','Phase 6'),
('Donholm','Phase 7'),
('Donholm','Phase 8'),
('Donholm','Greenfields'),
('Donholm','Old Donholm'),
('Donholm','Donholm Shopping Centre'),
('Greenspan','Greenspan Mall Area'),
('Greenspan','Donholm Border'),
('Greenspan','Tena Border'),
('Tena','Tena Estate'),
('Tena','Donholm Border'),
('Tena','Umoja Border'),
('Mowlem','Mowlem'),
('Mowlem','Umoja Border'),
('Mowlem','Kayole Border'),
('Umoja','Umoja I'),
('Umoja','Umoja II'),
('Umoja','Innercore'),
('Umoja','Tena'),
('Umoja','Umoja Market'),
('Umoja','Makadara'),
('Umoja','Hamza'),
('Umoja','Maringo'),
('Umoja','Jericho'),
('Umoja','Mbotela'),
('Umoja','Makongeni Border'),
('Maringo','Maringo'),
('Maringo','Hamza'),
('Maringo','Jericho Border'),
('Jericho','Ofafa Jericho'),
('Jericho','Jerusalem'),
('Jericho','Lumumba'),
('Jericho','Jericho Estate'),
('Harambee','Harambee Estate'),
('Harambee','Makadara Border'),
('Harambee','Viwandani Border'),
('Makongeni','Makongeni'),
('Makongeni','Harambee Border'),
('Makongeni','Bahati Border'),
('Bahati','Bahati'),
('Bahati','Kaloleni Border'),
('Bahati','Jericho Border'),
('Kaloleni','Kaloleni'),
('Kaloleni','Makongeni Border'),
('Kaloleni','Ofafa Border'),
('Viwandani','Viwandani'),
('Viwandani','Industrial Area Border'),
('Viwandani','Makadara Border'),
('South B','Plainsview'),
('South B','Golden Gate'),
('South B','Mariakani'),
('South B','South B Shopping Centre'),
('South B','Mukuru Border'),
('South B','Eastleigh'),
('South B','Section I'),
('South B','Section II'),
('South B','Section III'),
('South B','Eastleigh North'),
('South B','Eastleigh South'),
('South B','First Avenue'),
('South B','Second Avenue'),
('South B','Third Avenue'),
('South B','Twelfth Street'),
('South B','BBS Mall Area'),
('South B','Garissa Lodge Area'),
('Pumwani','Pumwani'),
('Pumwani','Majengo'),
('Pumwani','Shauri Moyo Border'),
('Pumwani','Gikomba Border'),
('California','California Estate'),
('California','Eastleigh Border'),
('California','Pumwani Border'),
('Shauri Moyo','Shauri Moyo'),
('Shauri Moyo','Pumwani Border'),
('Shauri Moyo','Eastleigh Border'),
('Majengo','Majengo'),
('Majengo','Gikomba Border'),
('Majengo','Pumwani Border'),
('Gikomba','Gikomba Market Area'),
('Gikomba','Eastleigh Border'),
('Gikomba','Pumwani Border'),
('Airbase','Airbase'),
('Airbase','Eastleigh North Border'),
('Airbase','Kamukunji Border'),
('Biafra','Biafra Estate'),
('Biafra','Eastleigh Border'),
('Biafra','Pangani Border'),
('Mlango Kubwa','Mlango Kubwa'),
('Mlango Kubwa','Mathare Border'),
('Mlango Kubwa','Eastleigh Border'),
('Mlango Kubwa','Nairobi Central'),
('Mlango Kubwa','CBD'),
('Mlango Kubwa','City Centre'),
('Mlango Kubwa','River Road'),
('Mlango Kubwa','Tom Mboya Street'),
('Mlango Kubwa','Moi Avenue'),
('Mlango Kubwa','Kimathi Street'),
('Mlango Kubwa','Kenyatta Avenue'),
('Landimawe','Landimawe'),
('Landimawe','South C Border'),
('Landimawe','Industrial Area Border'),
('Ngara','Kolobot Road'),
('Ngara','Kenya-Re'),
('Ngara','Fig Tree Area'),
('Ngara','Ngara Market'),
('Ngara','Forest Road'),
('Ngara','Pangani Border'),
('Pangani','Pangani'),
('Pangani','Agoi Road'),
('Pangani','Fairview Road'),
('Pangani','Pangani Shopping Centre'),
('Pangani','Ngara Border'),
('Ziwani','Ziwani'),
('Ziwani','Kariokor'),
('Ziwani','Ngara Border'),
('Ziwani','Bahati Border'),
('Kariokor','Kariokor Market'),
('Kariokor','Pangani Border'),
('Kariokor','Ngara Border'),
('Kariokor','Ziwani Border'),
('Race Course','Race Course'),
('Race Course','Ngara Border'),
('Race Course','Mathare North Border'),
('Hospital Hill','Hospital Hill'),
('Hospital Hill','Parklands Border'),
('Hospital Hill','Ngara Border'),
('Muthurwa','Market Area'),
('Muthurwa','Railway Quarters'),
('Muthurwa','Muthurwa Market'),
('Jamhuri','Jamhuri Phase I'),
('Jamhuri','Jamhuri Phase II'),
('Jamhuri','Askari Estate'),
('Jamhuri','Woodley Border'),
('Milimani','State House Road'),
('Milimani','Ralph Bunche Road'),
('Milimani','Valley Road Area'),
('Milimani','Hurlingham Border'),
('Upper Hill','Hospital Road'),
('Upper Hill','Elgon Road'),
('Upper Hill','Kilimanjaro Avenue'),
('Upper Hill','Mara Road'),
('Upper Hill','Britam Area'),
('Upper Hill','Community Area'),
('Upper Hill','Mathare'),
('Upper Hill','Mathare Area 1'),
('Upper Hill','Mathare Area 2'),
('Upper Hill','Mathare Area 3'),
('Upper Hill','Mathare Area 4A'),
('Upper Hill','Mathare Valley'),
('Upper Hill','Number 10'),
('Upper Hill','Bondeni'),
('Upper Hill','Hospital Border'),
('Huruma','Corner'),
('Huruma','Kiamaiko'),
('Huruma','Madoya'),
('Huruma','Huruma Market'),
('Huruma','Mathare Border'),
('Mabatini','Mabatini'),
('Mabatini','Mathare Border'),
('Mabatini','Huruma Border'),
('Ngei','Ngei'),
('Ngei','Huruma Border'),
('Ngei','Mathare North Border'),
('Hospital','Mathare Hospital Area'),
('Hospital','Mathare Valley'),
('Hospital','Mathare North Border'),
('Kiamaiko','Kiamaiko'),
('Kiamaiko','Huruma'),
('Kiamaiko','Eastleigh Border'),
('Kiamaiko','Madaraka'),
('Kiamaiko','Strathmore Area'),
('Kiamaiko','Madaraka Estate'),
('Kiamaiko','Naivasha Road Border'),
('Kiamaiko','Langata Road'),
('Muthangari','Muthangari'),
('Muthangari','James Gichuru'),
('Muthangari','Riverside Border'),
('Muthangari','Lavington Border'),
('Riverside','Riverside Drive'),
('Riverside','Riverside Square'),
('Riverside','Kileleshwa Border'),
('Riverside','Westlands Border'),
('Mukuru','Mukuru Kwa Njenga'),
('Mukuru','Mukuru Kwa Reuben'),
('Mukuru','Industrial Area Border'),
('Mukuru','Pipeline Border'),
('Mukuru','Syokimau'),
('Mukuru','Syokimau Town'),
('Mukuru','Gateway Mall Area'),
('Mukuru','Katani Road'),
('Mukuru','Mombasa Road'),
('Mlolongo','Mlolongo Town'),
('Mlolongo','Athi River Road'),
('Mlolongo','Mombasa Road'),
('Athi River','EPZ Area'),
('Athi River','Athi River Town'),
('Athi River','Greatwall'),
('Athi River','Mavoko'),
('Ongata Rongai','Maasai Mall Area'),
('Ongata Rongai','Rimpa'),
('Ongata Rongai','Kware'),
('Ongata Rongai','Nkoroi'),
('Ongata Rongai','Tuala Border'),
('Kiserian','Kiserian Town'),
('Kiserian','Pipeline Area'),
('Kiserian','Ngong Road Border'),
('Ngong','Kibiko'),
('Ngong','Matasia'),
('Ngong','Ngong Town'),
('Ngong','Bulbul'),
('Ngong','Vetland'),
('Kitengela','Kitengela Town'),
('Kitengela','Milimani'),
('Kitengela','Acacia'),
('Kitengela','Chuna'),
('Kitengela','New Valley'),
('Kitengela','Greatwall'),
('Ruiru','Membley'),
('Ruiru','Kimbo'),
('Ruiru','Kahawa Sukari Border'),
('Ruiru','Ruiru Town'),
('Ruiru','Githurai Border'),
('Juja','Juja Farm'),
('Juja','Witeithie'),
('Juja','Juja Town'),
('Juja','Kalimoni'),
('Thika','Section 9'),
('Thika','Landless'),
('Thika','Makongeni Thika'),
('Thika','Ngoigwa'),
('Thika','Thika Town');
